### ISSUE TITLE
Geometry of 10mw rwt

### ISSUE THREAD

**Issue by bharatchandraalla1996** [fzahle/DTU_10MW_RWT#1]
Dear Zahle, 

I hope you are fine and doing good. You have made an repository for DTU's 10MW RWT here. 

But, I don't find any files here and Can you please help me?

**Comment by fzahle** [comment]
you can find it here: https://rwt.windenergy.dtu.dk/dtu10mw/dtu-10mw-rwt.

I should delete this repo, not used.

**Comment by bharatchandraalla1996** [comment]
Thank you for your prompt reply.

But the .iges files are not opening in SOLIDWORKS.

Can you please help me?

**Comment by fzahle** [comment]
we haven't had anyone mention this before. but could you instead just import the ascii files somehow?

**Comment by bharatchandraalla1996** [comment]
Yeah but I tried in a different way. I imported the iges file into Ansys Spaceclaim and generated the parasolid file to use in Numeca's Hexpress for mesh generation. 

But, I'm not sure the accurate assemblying the whole geometry. Meanwhile, We are suppose to validate your CFD results with our in-house code result. So, could you please send me assembled CAD file?

**Comment by fzahle** [comment]
we don't actually really use CAD for surface meshing, we mesh it directly with a python tool based on the lofted surface, so I can't really help you on that. the surface mesh we have used is also available in the repo.

**Comment by bharatchandraalla1996** [comment]
Yes! But you still have the fully assembled CAD geometry right? And I need that!.

**Comment by fzahle** [comment]
the way the CAD files were made was by loading in the lofted surface as a database in Pointwise and then exporting it as IGES. So the only CAD surface I have is the one in the repo.

**Comment by bharatchandraalla1996** [comment]
Yes! There are CAD files in the repo. But they are separate parts. I want to compare the CFD results in the repo with our in-house code. 

The CFD results in the repo, has the geometry shown in the attachment. 
![Screenshot_20210416-120254_Drive](https://user-images.githubusercontent.com/82647803/115015790-1d6a4780-9eac-11eb-8462-ab28d175462b.jpg). So, I want the CAD file including rotor, hub and nacelle. Could you please sent me?

**Comment by fzahle** [comment]
solved via email.
